// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // Example: "Learn" section → manual top-level, auto sub-sections
    learnSidebar: [
      
      {
        type: 'category',
        label: 'Verifiable Trust',
        items: [
         
          {
            type: 'autogenerated',
            dirName: 'learn/verifiable-trust',  // auto-generate from this subfolder
          },
          
        ],
      },
      
      
      {
        type: 'category',
        label: 'Verifiable Public Registry',
        items: [
         
          {
            type: 'autogenerated',
            dirName: 'learn/verifiable-public-registry',  // auto-generate from this subfolder
          },
          
        ],
      },
     
    ],
  
    useSidebar: [
        {
          type: 'category',
          label: 'Use Verana',
          items: [
            'use/intro',
            
          ],
        },
        {
            type: 'category',
            label: 'Getting Started',
            items: [
             
              {
                type: 'autogenerated',
                dirName: 'use/getting-started',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Ecosystems',
            items: [
             
              {
                type: 'autogenerated',
                dirName: 'use/ecosystems',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Verifiable User Agent Builders',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'use/verifiable-user-agent-builders',  // auto-generate from this subfolder
              },
            ],
          },
    ],

    networkSidebar: [
        {
          type: 'category',
          label: 'Introduction',
          items: [
            {
              type: 'autogenerated',
              dirName: 'network/introduction',  // auto-generate from this subfolder
            },
            
          ],
        },
        {
            type: 'category',
            label: 'Environments',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'network/environments',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Running a Node',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'network/run-a-node',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Interacting with Modules',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'network/modules',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Governance and Upgrades',
            items: [
              
              {
                  type: 'autogenerated',
                  dirName: 'network/governance',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Testing and Debugging',
            items: [
              
              {
                  type: 'autogenerated',
                  dirName: 'network/testing',  // auto-generate from this subfolder
              },
            ],
          },
    ],
    
    
    // You can add more sidebars if needed (ex: API reference, specs, etc.)
  };
  
  module.exports = sidebars;
  