// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // Example: "Learn" section → manual top-level, auto sub-sections
    learnSidebar: [
      
      {
        type: 'category',
        label: 'Verifiable Trust',
        items: [
         
          {
            type: 'autogenerated',
            dirName: 'learn/verifiable-trust',  // auto-generate from this subfolder
          },
          
        ],
      },
      
      
      {
        type: 'category',
        label: 'Verifiable Public Registry',
        items: [
         
          {
            type: 'autogenerated',
            dirName: 'learn/verifiable-public-registry',  // auto-generate from this subfolder
          },
          
        ],
      },
     
    ],
  
    useSidebar: [
        
        {
            type: 'category',
            label: 'Ecosystems',
            items: [
             
              {
                type: 'autogenerated',
                dirName: 'use/ecosystems',  // auto-generate from this subfolder
              },
              
            ],
          },
        {
            type: 'category',
            label: 'DID Directory',
            items: [
             
              {
                type: 'autogenerated',
                dirName: 'use/did-directory',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Verifiable Service Builders',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'use/verifiable-service-builders',  // auto-generate from this subfolder
              },
            ],
          },
          {
            type: 'category',
            label: 'Verifiable User Agent Builders',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'use/verifiable-user-agent-builders',  // auto-generate from this subfolder
              },
            ],
          },
    ],

    runSidebar: [
        {
          type: 'category',
          label: 'Introduction',
          items: [
            {
              type: 'autogenerated',
              dirName: 'run/introduction',  // auto-generate from this subfolder
            },
            
          ],
        },
         {
            type: 'category',
            label: 'Run the Network',
            items: [
              {
                type: 'doc',
                id: 'run/network/welcome', 
              },
              {
            type: 'category',
            label: 'Environments',
            items: [
              
              
              {
                type: 'autogenerated',
                dirName: 'run/network/environments',  // auto-generate from this subfolder
              },
              
            ],
          },
                {
            type: 'category',
            label: 'Running a Node',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'run/network/run-a-node',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Interacting with Modules',
            items: [
              
              {
                type: 'autogenerated',
                dirName: 'run/network/modules',  // auto-generate from this subfolder
              }, 
              
            ],
          },
          {
            type: 'category',
            label: 'Governance and Upgrades',
            items: [
              
              {
                  type: 'autogenerated',
                  dirName: 'run/network/governance',  // auto-generate from this subfolder
              },
              
            ],
          },
          {
            type: 'category',
            label: 'Testing and Debugging',
            items: [
              
              {
                  type: 'autogenerated',
                  dirName: 'run/network/testing',  // auto-generate from this subfolder
              },
            ],
          },
              
            ],
          },


          
          {
            type: 'category',
            label: 'Deploy Other Components',
            items: [
              
              {
                  type: 'autogenerated',
                  dirName: 'run/other-component-deployment',  // auto-generate from this subfolder
              },
            ],
          },
    ],
    
    
    // You can add more sidebars if needed (ex: API reference, specs, etc.)
  };
  
  module.exports = sidebars;
  