# .github/workflows/deploy.yml

name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy when pushing to main

  workflow_dispatch:

permissions:
      contents: read
      pages: write
      id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use the Node.js version compatible with your Docusaurus build

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        id: deployment
        if: >
          success()
          && github.ref == 'refs/heads/main'
          && github.repository == 'verana-labs/verana-docs'
        uses: actions/deploy-pages@v4
  